import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TernSecureProvider } from "./providers/TernSecureProvider";
//import { TernSecureProvider, SignOut } from "@tern-secure/nextjs";
import { SignOut } from "./providers/components/sign-out-construct-v2";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TernSecureProvider>
          {children}
          <SignOut />
        </TernSecureProvider>
      </body>
    </html>
  );
}
