import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import { TernSecureProvider } from "./providers/TernSecureProvider";
import { TernSecureProvider, UserButton } from "@tern-secure/nextjs";
//import { SignOut } from "./providers/components/sign-out-construct-v2";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TernSecureProvider
          appCheck={{
            provider: "reCaptchaV3",
            siteKey: "6LfzGRgsAAAAAGEvbwbcLgT4IHWmuWv4kEDRA5hi",
            isTokenAutoRefreshEnabled: true,
          }}
          ternUIUrl="https://cdn.jsdelivr.net/npm/@tern-secure/auth@1.1.0-canary.v20251207162402/dist/ternsecure.browser.js"
          persistence="browserCookie"
          requiresVerification={false}
        >
          {children}
          <UserButton />
        </TernSecureProvider>
      </body>
    </html>
  );
}
